// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiVggtk4Olld76mSER17z6mkaSmv5fPHs',
    appId: '1:474696383162:web:6ff845536eb4eb20fe2083',
    messagingSenderId: '474696383162',
    projectId: 'safepulse-d8a5d',
    authDomain: 'safepulse-d8a5d.firebaseapp.com',
    storageBucket: 'safepulse-d8a5d.firebasestorage.app',
    measurementId: 'G-1E1R13J6EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtUgw9sWUlF6Z_YZYN11o89js3CkY0-Ck',
    appId: '1:474696383162:android:8201a75219cad424fe2083',
    messagingSenderId: '474696383162',
    projectId: 'safepulse-d8a5d',
    storageBucket: 'safepulse-d8a5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSRFJ3t9S49_RjnwFnHvSQHW5HJhPu5ko',
    appId: '1:474696383162:ios:ee96789be6f01217fe2083',
    messagingSenderId: '474696383162',
    projectId: 'safepulse-d8a5d',
    storageBucket: 'safepulse-d8a5d.firebasestorage.app',
    iosBundleId: 'com.example.safepulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSRFJ3t9S49_RjnwFnHvSQHW5HJhPu5ko',
    appId: '1:474696383162:ios:ee96789be6f01217fe2083',
    messagingSenderId: '474696383162',
    projectId: 'safepulse-d8a5d',
    storageBucket: 'safepulse-d8a5d.firebasestorage.app',
    iosBundleId: 'com.example.safepulse',
  );
}
